Repository sandydoo/ember-google-maps, pull requests merged in 2021-08, with the labels that each got.

#136 Document `ember-google-maps-markerclustererplus`
  docs/app/controllers/docs.js
  docs/app/index.html
  docs/app/router.js
  docs/app/routes/docs/clustering.js
  docs/app/templates/application.hbs
  docs/app/templates/docs/clustering.hbs
  docs/app/templates/docs/complex-ui.hbs
  docs/code-snippets/basic-cluster.hbs
  docs/code-snippets/cluster-events.hbs
  docs/code-snippets/install-markerclustererplus.sh
  docs/package.json
  docs/yarn.lock
Labels: documentation

#137 Pre-render the clustering docs
  docs/ember-cli-build.js
Labels: documentation

#138 Pre-render docs when building with Embroider
  docs/ember-cli-build.js
  docs/package.json
  docs/yarn.lock
Labels: documentation

#139 Fix teardown errors in FastBoot
  addon/component-managers/map-component-manager.js
Labels: bug

#142 Refactor AST plugins to match new plugin format
  lib/ast-transforms/addon-factory.js
  lib/ast-transforms/canvas-enforcer.js
  lib/ast-transforms/treeshaker.js
Labels: internal

#143 Fix test-waiters import errors in embroider builds
  package.json
  yarn.lock
Labels: dependencies, internal

#141 Fix CI for external PRs
  .github/scripts/setup-ci.sh
  .github/workflows/ci.yml
  docs/.gitignore
Labels: internal

#140 Return the `google` global from the API service if Google Maps has already been loaded
  addon/services/google-maps-api.js
Labels: bug

#144 Cache yarn's global cache of packages in CI
  .github/workflows/ci.yml
Labels: internal

#145 Dedupe yarn packages
  docs/yarn.lock
  yarn.lock
Labels: dependencies
